name: Loto
favicon: null
layout_spectrum: 0.24832
typography_spectrum: 0.83959
title: 'Loto, flor de Loto.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#feffed'
    - '#283a00'
    - '#6a7b10'
    - '#b48daf'
  brandStrength: 0
  lightness: 0.445687796222046
  saturation: 0.601395309669897
  rhythmicContrast: 0.2682119735982269
purpose: []
