name: Loto
favicon: null
layout_spectrum: 0.7509094192646444
typography_spectrum: 0.9171375602018088
title: 'Loto, flor de Loto.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.05176355061121285
  lightness: 0.445687796222046
  saturation: 0.601395309669897
  rhythmicContrast: 0.2682119735982269
purpose: []
